languageCode:           "en"
title:                  "Bootstrap"
# baseURL:                "https://getbootstrap.com"
baseURL:                "https://hugo-widebs5-example.pages.dev/"
theme:     "github.com/juggernautjp/hugo-widebs5-theme"
# if git clone github.com/juggernautjp/hugo-widebs5-theme theme/hugo-widebs5-theme
# theme:     "hugo-widebs5-theme"

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY
  gotemplates:
    allowActionJSTmpl: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

# publishDir:             "_site"
publishDir:             "public"

module:
  hugoVersion:
     extended: true
     min: "0.109.0"
     max: ""
  mounts:
    - source: "assets"
      target: "assets"
  imports:
    - path: "github.com/twbs/bootstrap"
      mounts:
        - source: "scss"
          target: "assets/bootstrap/scss"
        - source: "js"
          target: "assets/bootstrap/js"
        - source: "dist"
          target: "static/bootstrap"
    - path: "github.com/juggernautjp/hugo-widebs5-theme"
      mounts:
        - source: "archetypes"
          target: "archetypes"
        - source: "assets"
          target: "assets"
        - source: "content"
          target: "content"
        - source: "layouts"
          target: "layouts"
    - path: "github.com/gohugoio/hugo-mod-jslibs-dist/popperjs/v2"
# For import Docsy Theme's dependencies/assets/sccs/_vendor
#    - source:           "assets/bootstrap/scss/_vendor"
#      target:           "assets/vendor/bootstrap/scss/vendor"
#    - source:           "scss"
#      target:           "assets/vendor/bootstrap/scss"
#
#    - path:             "github.com/juggernautjp/hugo-widebs5-theme"
#  mounts:
#    - source:           dist
#      target:           static/docs/5.3/dist
#    - source:           site/assets
#      target:           assets
#    - source:           site/content
#      target:           content
#    - source:           site/data
#      target:           data
#    - source:           site/layouts
#      target:           layouts
#    - source:           site/static
#      target:           static
#    - source:           site/static/docs/5.3/assets/img/favicons/apple-touch-icon.png
#      target:           static/apple-touch-icon.png
#    - source:           site/static/docs/5.3/assets/img/favicons/favicon.ico
#      target:           static/favicon.ico

params:
  subtitle:             "The most popular HTML, CSS, and JS library in the world."
  description:          "Powerful, extensible, and feature-packed frontend toolkit. Build and customize with Sass, utilize prebuilt grid system and components, and bring projects to life with powerful JavaScript plugins."
  authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"

  current_version:      "5.3.0-alpha1"
  current_ruby_version: "5.3.0-alpha1"
  docs_version:         "5.3"
  rfs_version:          "v9.0.6"
  github_org:           "https://github.com/juggernautjp"
  repo:                 "https://github.com/juggernautjp/hugo-widebs5-example"
  twitter:              "getbootstrap"
  opencollective:       "https://opencollective.com/bootstrap"
  blog:                 "https://blog.getbootstrap.com/"
  themes:               "https://themes.getbootstrap.com/"
  icons:                "https://icons.getbootstrap.com/"
  swag:                 "https://cottonbureau.com/people/bootstrap"

  download:
    source:             "https://github.com/twbs/bootstrap/archive/v5.3.0.zip"
    dist:               "https://github.com/twbs/bootstrap/releases/download/v5.3.0/bootstrap-5.3.0-dist.zip"
    dist_examples:      "https://github.com/twbs/bootstrap/releases/download/v5.3.0/bootstrap-5.3.0-examples.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    css_hash:         "sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
    css_rtl:          "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.rtl.min.css"
    css_rtl_hash:     "sha384-PJsj/BTMqILvmcej7ulplguok8ag4xFTPryRq8xevL7eBYSmpXKcbNVuy+P0RMgq"
    js:               "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
    js_hash:          "sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
    js_bundle:        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    popper_hash:      "sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    popper_esm:       "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js"

  anchors:
    min: 2
    max: 5


params:
  options:
    bsa_path: ""

